#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

npm i --no-audit --no-fund
npm audit
npm run license-check
npm run dep-check
npm run no-console
npm run test:cov
npm run badge:cov
git add badges/\*
npm run changelog
git add changelog.md
