name: 'Size Limit'

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  size-limit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for size-limit config
        id: has_config
        run: |
          if [ -f "./.size-limit.js" ] || [ -f "./size-limit.config.js" ] || [ -f "./.size-limit.json" ]; then
            echo "found=true" >> "$GITHUB_OUTPUT"
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Run size-limit
        if: steps.has_config.outputs.found == 'true'
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
